import Navbar from "../components/Navbar";
import "./globals.css";
import "../fonts/fonts.css";
import { GlobalContextProvider } from "./components/common/store";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="root">
        <GlobalContextProvider>
          <Navbar />

          {children}
        </GlobalContextProvider>
      </body>
    </html>
  );
}
